/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./overlay.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131314",
        "outline-variant": "#464554",
        "on-primary-container": "#e7e4ff",
        "on-tertiary": "#472a00",
        "surface-variant": "#353436",
        "inverse-surface": "#e5e2e3",
        "outline": "#918f9f",
        "on-primary": "#1c0b9f",
        "inverse-primary": "#4f4ccd",
        "surface-container-highest": "#353436",
        "surface-tint": "#c2c1ff",
        "on-background": "#e5e2e3",
        "on-surface-variant": "#c7c4d6",
        "on-secondary-fixed": "#002113",
        "tertiary-container": "#915b00",
        "surface-container-lowest": "#0e0e0f",
        "on-secondary-fixed-variant": "#005236",
        "tertiary": "#ffb95f",
        "tertiary-fixed": "#ffddb8",
        "surface": "#131314",
        "primary-fixed": "#e2dfff",
        "surface-container": "#201f20",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#2a2a2b",
        "primary-fixed-dim": "#c2c1ff",
        "on-secondary": "#003824",
        "error": "#ffb4ab",
        "on-surface": "#e5e2e3",
        "on-primary-fixed": "#0c006a",
        "on-secondary-container": "#00311f",
        "on-tertiary-fixed": "#2a1700",
        "on-primary-fixed-variant": "#3631b4",
        "secondary": "#4edea3",
        "on-tertiary-container": "#ffe1c2",
        "primary": "#c2c1ff",
        "tertiary-fixed-dim": "#ffb95f",
        "secondary-container": "#00a572",
        "inverse-on-surface": "#313031",
        "on-error": "#690005",
        "primary-container": "#5856d6",
        "surface-container-low": "#1c1b1c",
        "error-container": "#93000a",
        "surface-bright": "#39393a",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary-fixed-variant": "#653e00",
        "background": "#131314",
        "secondary-fixed-dim": "#4edea3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "grid-columns": "12",
        "grid-gutter": "20px",
        "unit": "4px",
        "stack-gap": "12px",
        "container-padding": "24px",
        "section-gap": "40px"
      },
      fontFamily: {
        "display-metrics": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "label-xs": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
